name: Npm package

on:
  push:
    branches:
      - "*"
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Nodejs v14.20.0
        uses: actions/setup-node@master
        with:
          node-version: 14.20.0

      # - name: Build
      #   run: npm ci

      # - name: Test
      #   run: npm test

      # - uses: IgnusG/jest-report-action@v2.3.3
      #   if: always()
      #   with:
      #     access-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to Npm
        if: contains(github.ref, 'refs/tags/v')
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
